# Generated by Django 5.0.2 on 2024-03-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='students_registration', to='core.user', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='suscription', to='core.user', verbose_name='Estudiante'),
        ),
    ]
